name: Build and Push Docker Image

on:
  push:
    branches:
      - "test-optimized-dockerfile"
  pull_request:
    branches:
      - "test-optimized-dockerfile"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Clone lidarr-flac2mp3 repository
    - name: Clone lidarr-flac2mp3
      run: |
        git clone https://github.com/youegraillot/lidarr-flac2mp3.git lidarr-flac2mp3
        cd lidarr-flac2mp3
        git checkout f755bb2c7e2922244f02287edb03d0484e0a5f05

    # Debugging step: List repository contents
    - name: Debugging: List lidarr-flac2mp3 contents
      run: |
        echo "Listing lidarr-flac2mp3 directory contents:"
        ls -R lidarr-flac2mp3

    # Set up QEMU for cross-platform builds
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Build and push Docker image
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/lidarr-on-steroids:test
